
cargo-features = ["edition2024"]
[package]
name = "rsum"
version = "0.1.0"
edition = "2024"

[lib]
name = "rust_native_solana"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.7"
pinocchio = "0.9.2"
solana-program = "2.2.1"
